swagger: "2.0"
info:
  description: "Product Service Swagger Documentation"
  version: 2.0.0
  title: "Product Service Swagger Documentation"
host: "zz73b76oel.execute-api.eu-west-1.amazonaws.com"
basePath: "/rds"
schemes:
- "https"
paths:
  /products:
    get:
      tags:
      - "Product Service"
      summary: "List All Products"
      description: "Returns Array of All Products"
      operationId: "getProductsList"
      produces:
      - "application/json"
      responses:
        "200":
          description: "Successful Operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Product"
        "500":
          description: "Internal Server Error"
    post:
      tags:
      - "Product Service"
      summary: "Create a New Product"
      description: "Returns Created Product"
      operationId: "createProduct"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "newProductToCreate"
        in: "body"
        description: "New product that needs to be added"
        schema:
          $ref: "#/definitions/Product"
      responses:
        "200":
          description: "Successful Operation"
          schema:
            $ref: "#/definitions/Product"
        "400":
          description: "Invalid Request Body (Bad Request)"
        "500":
          description: "Internal Server Error"
          
  /products/{id}:
    get:
      tags:
      - "Product Service"
      summary: "Find Product by Id"
      description: "Returns a Single Product or Not Found Error"
      operationId: "getProductById"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "Id of Product to Return"
        required: true
        type: "string"
        format: "uuid"
      responses:
        "200":
          description: "Successful Operation"
          schema:
            $ref: "#/definitions/Product"
        "400":
          description: "Invalid Id Supplied (Bad Request)"
        "404":
          description: "Product Not Found"
        "500":
          description: "Internal Server Error"

definitions:
  Product:
    type: "object"
    required:
    - "title"
    properties:
      id:
        type: "string"
        format: "uuid"
        readOnly: true
      title:
        type: "string"
        example: "New Product Title"
      description:
        type: "string"
        example: "New Product Description"
      price:
        type: "number"
        format: "float"
        example: 55.55
        minimum: 0
      count:
        type: "integer"
        example: 5
        minimum: 0
      src:
        type: "string"
        format: "uri"
        example: "https://images.unsplash.com/photo-1586391159312-e26d25fa4c42?width=500"